KS-1-1 add variables for numbers of orders and thank yoy message
antonio92220/KotlinStudy_antohen_suh pull request #2
Opened 2024-10-13 19:42 UTC by antonio92220

Добавил 2 переменные: 
1) numberOfOrders с типом uInt потому что непонятно каких масштабов магазин, можно там ультра оптовые закупки, нужно было заменить на типо поменьше (типо Short)?
2) thankYouMessage - статичная неизменяемая переменная, подумал что текст не будет меняться по ходу кода 
В задаче не было указано, но решил, что надпись благодарственная должна выводиться, если неправильно, то поправлю

2024-10-14 18:37 UTC, ievetrovdev requested changes
Привет! великолепное оформление пулл реквеста, все нейминги корректные)

Я оставил комментарий для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-10-14 18:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +Пишем логику экрана приложения для интернет-магазина. Представим, что у интернет-магазина было 75 заказов.
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-10-14 18:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    var numberOfOrders : UInt = 75u
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-10-14 18:52 UTC, antonio92220 commented
Поправил замечания, спасибо)

2024-10-15 09:41 UTC, ievetrovdev approved these changes
Все верно!

Теперь эту ветку можно мержить в мастер. напомню, перед созданием новой ветки надо переключиться в мастер, обновить его (чтобы слитые изменения прилетели в локальный проект) и только тогда бранчиться

2024-10-15 09:45 UTC, merged