KS-1-2 adding variables for numbers of empoyees and output to the con…
antonio92220/KotlinStudy_antohen_suh pull request #3
Opened 2024-10-13 20:04 UTC by antonio92220

Добавил новую переменную для подсчета количетсво сотрудников магазина и добавил вывод сотрудников, количества заказов и сообщения " спасибо за покупку"

2024-10-14 18:40 UTC, ievetrovdev requested changes
Чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-10-14 18:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +    val numberOfOrders : UInt = 75u
Хорошо, что используешь тип U, однако, все таки в большинстве коммерческих проектов такая точность не применяется. Если это не какая-нибудь высокоточная программа, где каждый байт важен, то в остальных случаях это "экономия на спичках".

2024-10-14 18:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +    println("Количество товара - "+numberOfOrders)
Так как мы пишем на Котлин, лучше все таки использовать не конкатенацию (сложение), а интерполяцию)

2024-10-14 18:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +    var numberOfEmployees : UInt = 2000u
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-10-14 18:41 UTC, ievetrovdev requested changes

2024-10-14 18:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> + – Далее нужно сделать так, чтобы программа хранила количество работников данного интернет-магазина (2000).
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-10-14 19:01 UTC, antonio92220 commented
Поправил все по комментам

2024-10-15 09:44 UTC, ievetrovdev approved these changes
Теперь эту ветку можно сливать в мастер. Перед созданием новой ветки (обязательно из мастера) не забудь сделать его Update, чтобы слитые изменения прилетели с сервера в локальный проект.

2024-10-15 09:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +    println("Количество товара - " + numberOfOrders)
На будущее, давай везде будем использовать интерполяцию, сейчас аппрув!

2024-10-15 09:47 UTC, merged