KS-1-4 added new variables with data about Gagarin's flight
antonio92220/KotlinStudy_antohen_suh pull request #5
Opened 2024-10-13 21:00 UTC by antonio92220

добавил новые переменные с данными о полете Гагарина

2024-10-14 18:44 UTC, ievetrovdev requested changes

2024-10-14 18:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +И выведи все эти переменные в столбик (каждая с новой строки).
Комментарии, не относящиеся к решению или не несущие никакой полезной нагрузки для будущего себя или других разработчиков в команде – лучше не оставлять в продакшн коде.

2024-10-14 18:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +
Больше одной пустой строки старайся не оставлять на будущее, предлагаю сразу привыкать писать красивый код согласно конвенции стиля Kotlin

2024-10-14 18:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val partOfDay : Float = 0.075f
Не забывай прожимать автоформатирование перед коммитом.

2024-10-14 18:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    println(length)
Рекомендую блок с объявлением переменных отделять пустой строкой от всего остального кода. Так код будет менее монолитным, что улучшить читабельность.

2024-10-14 19:06 UTC, antonio92220 commented
Поправил по комментариям

2024-10-15 09:45 UTC, ievetrovdev approved these changes
Прекрасно!

2024-10-15 09:47 UTC, merged